# Generated by Django 2.2.10 on 2020-02-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('FUN', 'fundacja'), ('ORG', 'organizacja pozarządowa'), ('ZBL', 'zbiórka lokalna')], default='FUN', max_length=3),
        ),
    ]
