# Generated by Django 2.2.10 on 2020-02-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_auto_20200219_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='categories',
            field=models.ManyToManyField(related_name='cat_instit', to='charity.Category'),
        ),
    ]
